# Generated by Django 5.0.14 on 2026-05-09 21:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_invoice_cliente_condicion_iva'),
        ('customers', '0002_alter_customer_tax_condition'),
        ('payments', '0001_initial'),
        ('sales', '0002_add_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Cliente que realiza el pago (null = walk-in o anticipos sin cliente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha efectiva del cobro'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('debit_card', 'Tarjeta de Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('other', 'Otro')], default='cash', help_text='Medio de pago utilizado', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas adicionales sobre el pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Número de referencia: transferencia, cheque, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Factura específica a la que se imputa (OPCIONAL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='bills.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas sobre la alocación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del pago recibido', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Anulado')], db_index=True, default='pending', help_text='Estado del pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto imputado a esta alocación', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(help_text='Pago al que pertenece esta alocación', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='sale',
            field=models.ForeignKey(help_text='Venta a la que se imputa (OBLIGATORIO)', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'date'], name='payments_pa_custome_8bef44_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'date'], name='payments_pa_status_41526a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'sale'], name='payments_pa_payment_c9df7a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='payments_pa_invoice_16fb19_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gt', 0)), name='allocation_amount_positive'),
        ),
    ]
