# Generated by Django 5.0.14 on 2026-08-15 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_payment_amount_constraint'),
        ('payments', '0002_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentallocation',
            managers=[
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
