# Generated by Django 5.0.14 on 2026-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_payment_amount_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('debit_card', 'Tarjeta de Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('credit_note', 'Nota de Crédito'), ('other', 'Otro')], default='cash', help_text='Medio de pago utilizado', max_length=20),
        ),
    ]
