# Generated by Django 5.0.14 on 2026-03-31 14:33

import common.models
import django.core.validators
import django.db.models.deletion
import suppliers.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre.', max_length=150, unique=True)),
                ('color', models.CharField(default='#6366F1', help_text='Color hexadecimal para identificación visual (ej: #6366F1)', max_length=7, verbose_name='Color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Etiqueta de Proveedor',
                'verbose_name_plural': 'Etiquetas de Proveedores',
                'ordering': ['name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('business_name', models.CharField(help_text='Nombre legal de la empresa o nombre completo de la persona.', max_length=200, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, default='', help_text='Nombre comercial o fantasía (opcional).', max_length=200, verbose_name='Nombre Comercial')),
                ('cuit', models.CharField(blank=True, help_text='Formato: XX-XXXXXXXX-X (Opcional)', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El formato debe ser XX-XXXXXXXX-X', regex='^\\d{2}-\\d{8}-\\d{1}$'), suppliers.models.Supplier.validate_cuit_checksum], verbose_name='CUIT')),
                ('tax_condition', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento')], default='RI', max_length=10, verbose_name='Condición IVA')),
                ('email', models.EmailField(blank=True, default='', help_text='Email principal de contacto.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('website', models.URLField(blank=True, default='', verbose_name='Sitio Web')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Banco')),
                ('cbu', models.CharField(blank=True, default='', help_text='Clave Bancaria Uniforme (22 dígitos).', max_length=22, verbose_name='CBU')),
                ('bank_alias', models.CharField(blank=True, default='', max_length=100, verbose_name='Alias bancario')),
                ('contact_person', models.CharField(blank=True, default='', help_text='Nombre del vendedor o representante comercial.', max_length=200, verbose_name='Persona de contacto')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de contacto')),
                ('payment_term', models.IntegerField(default=0, help_text='Días de plazo para pago (0 = contado, 30, 60, 90).', verbose_name='Plazo de pago (días)')),
                ('payment_day_of_month', models.IntegerField(blank=True, help_text='Día del mes en que se paga (ej: 15). Null = desde fecha factura.', null=True, verbose_name='Día de pago del mes')),
                ('early_payment_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento por pronto pago.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento pronto pago (%)')),
                ('delivery_days', models.IntegerField(blank=True, help_text='Plazo de entrega promedio en días.', null=True, verbose_name='Plazo de entrega (días)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('last_price_list_date', models.DateField(blank=True, help_text='Fecha de la última lista de precios recibida del proveedor.', null=True, verbose_name='Fecha última lista de precios')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha última compra')),
                ('last_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto última compra')),
                ('total_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma total de todas las compras realizadas a este proveedor.', max_digits=14, verbose_name='Total comprado histórico')),
                ('current_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendiente de pago al proveedor.', max_digits=14, verbose_name='Deuda actual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('tags', models.ManyToManyField(blank=True, related_name='suppliers', to='suppliers.suppliertag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['cuit'], name='suppliers_s_cuit_3d0efb_idx'), models.Index(fields=['business_name'], name='suppliers_s_busines_a00fdc_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('cuit', None), _negated=True), models.Q(('cuit', ''), _negated=True)), fields=('cuit',), name='unique_supplier_cuit_if_not_null'),
        ),
    ]
