# Generated by Django 5.0.14 on 2026-08-21 17:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='suppliertag',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='early_payment_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento por pronto pago.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento pronto pago (%)'),
        ),
    ]
