# Generated by Django 5.0.14 on 2026-08-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_expenses',
            field=models.BooleanField(default=False),
        ),
    ]
