# Generated by Django 5.0.14 on 2026-08-21 17:39

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_can_manage_expenses'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emaillog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='registrationrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CoreUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userlog',
            managers=[
            ],
        ),
    ]
