# Generated by Django 5.0.14 on 2026-03-31 14:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_compr', models.IntegerField(choices=[(1, 'FACTURA A'), (2, 'NOTA DEBITO A'), (3, 'NOTA CREDITO A'), (6, 'FACTURA B'), (7, 'NOTA DEBITO B'), (8, 'NOTA CREDITO B'), (81, 'TIQUE FACTURA A'), (82, 'TIQUE FACTURA B'), (83, 'TIQUE CONSUMIDOR FINAL')], help_text='Tipo de comprobante (Factura A, B, etc.)')),
                ('punto_venta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_compr', models.DateField(help_text='Fecha del comprobante')),
                ('cbte_asoc_tipo', models.IntegerField(blank=True, null=True)),
                ('cbte_asoc_pto_vta', models.IntegerField(blank=True, null=True)),
                ('cbte_asoc_numero', models.IntegerField(blank=True, null=True)),
                ('fecha_vto_pago', models.DateField(blank=True, help_text='Fecha vencimiento pago', null=True)),
                ('doc_cliente_tipo', models.IntegerField(choices=[(80, 'CUIT'), (86, 'CUIL'), (96, 'DNI')])),
                ('doc_cliente', models.CharField(help_text='CUIT/CUIL/DNI del cliente', max_length=20)),
                ('razon_social_cliente', models.CharField(max_length=255)),
                ('condicion_iva_receptor', models.IntegerField(default=5, help_text='ID condición IVA del receptor (RG 5616). 1=RI, 4=Exento, 5=CF, 6=Mono')),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cae', models.CharField(blank=True, help_text='Código de Autorización Electrónica', max_length=14)),
                ('fecha_vto_cae', models.DateField(blank=True, help_text='Fecha de vencimiento del CAE', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente (enviado a ARCA)'), ('AUTORIZADO', 'Autorizado (CAE obtenido)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('respuesta_arca_json', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de ARCA')),
                ('error_msg', models.TextField(blank=True, help_text='Mensaje de error si ARCA rechazó')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(blank=True, help_text='Usuario que creó el comprobante', max_length=255)),
            ],
            options={
                'verbose_name': 'Comprobante ARCA',
                'verbose_name_plural': 'Comprobantes ARCA',
            },
        ),
        migrations.CreateModel(
            name='ComprobRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=21, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionARCA',
            fields=[
                ('empresa_cuit', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('ambiente', models.CharField(choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], default='homologacion', max_length=20)),
                ('ruta_certificado', models.CharField(help_text='Ruta absoluta a archivo .pem con certificado + clave privada', max_length=500)),
                ('password_certificado', models.CharField(blank=True, help_text='Contraseña del certificado si está protegido', max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('punto_venta', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración ARCA',
                'verbose_name_plural': 'Configuraciones ARCA',
            },
        ),
        migrations.CreateModel(
            name='LogARCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('WSAA_LOGIN', 'Login WSAA'), ('WSAA_ERROR', 'Error WSAA'), ('FE_AUTORIZAR', 'Autorizar comprobante'), ('FE_ERROR', 'Error FE'), ('FE_CONSULTAR', 'Consultar CAE')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cuit', models.CharField(max_length=15)),
                ('servicio', models.CharField(max_length=50)),
                ('request_xml', models.TextField(blank=True, default='')),
                ('response_xml', models.TextField(blank=True, default='')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Log ARCA',
                'verbose_name_plural': 'Logs ARCA',
            },
        ),
        migrations.CreateModel(
            name='WSAAToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(db_index=True, max_length=15)),
                ('servicio', models.CharField(choices=[('wsfe', 'Facturación Electrónica v1'), ('wsfe_v2', 'Facturación Electrónica v2')], max_length=20)),
                ('ambiente', models.CharField(choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], max_length=20)),
                ('token', models.TextField()),
                ('sign', models.TextField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Token WSAA',
                'verbose_name_plural': 'Tokens WSAA',
            },
        ),
    ]
