# Generated by Django 5.0.14 on 2026-03-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afip', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Venta que originó este comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_arca', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='comprobrenglon',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='afip.comprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='empresa_cuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afip.configuracionarca'),
        ),
        migrations.AddField(
            model_name='logarca',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afip.comprobante'),
        ),
        migrations.AddIndex(
            model_name='wsaatoken',
            index=models.Index(fields=['cuit', 'servicio', 'ambiente'], name='afip_wsaato_cuit_a96774_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wsaatoken',
            unique_together={('cuit', 'servicio', 'ambiente')},
        ),
        migrations.AlterUniqueTogether(
            name='comprobrenglon',
            unique_together={('comprobante', 'numero_linea')},
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['empresa_cuit', 'estado'], name='afip_compro_empresa_1cde76_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['fecha_compr'], name='afip_compro_fecha_c_3a181d_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['doc_cliente'], name='afip_compro_doc_cli_cdd511_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('empresa_cuit', 'tipo_compr', 'punto_venta', 'numero')},
        ),
        migrations.AddIndex(
            model_name='logarca',
            index=models.Index(fields=['cuit', 'timestamp'], name='afip_logarc_cuit_7ea9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='logarca',
            index=models.Index(fields=['tipo'], name='afip_logarc_tipo_783cd3_idx'),
        ),
    ]
