# Generated by Django 5.0.14 on 2026-07-02 13:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0003_expand_servicio_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobrenglon',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
