# Generated by Django 5.0.14 on 2026-05-10 00:39

import common.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(help_text='Nombre de la categoría (ej: "Alquiler Local")', max_length=100)),
                ('type', models.CharField(choices=[('salary', 'Sueldos y Jornales'), ('rent', 'Alquiler y Expensas'), ('utilities', 'Servicios (Luz, Gas, Internet)'), ('transport', 'Flete y Transporte'), ('marketing', 'Marketing y Publicidad'), ('taxes', 'Impuestos y Tasas'), ('maintenance', 'Mantenimiento'), ('supplies', 'Insumos Operativos'), ('other', 'Otros Gastos')], db_index=True, help_text='Tipo de gasto para agrupación en reportes', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción adicional (opcional)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(help_text='Descripción del gasto (ej: "Alquiler Mayo 2026")', max_length=255)),
                ('amount_neto', models.DecimalField(decimal_places=2, help_text='Monto sin IVA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto de IVA (21% en Argentina)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_total', models.DecimalField(decimal_places=2, help_text='Neto + IVA (se auto-calcula en clean())', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(db_index=True, help_text='Cuándo se generó/devengó el gasto (para P&L)')),
                ('payment_date', models.DateField(blank=True, db_index=True, help_text='Cuándo se pagó (para Cash Flow) — opcional', null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='¿Ya fue pagado?')),
                ('period_year', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Año del período contable (auto-asignado)', null=True)),
                ('period_month', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Mes del período contable (1-12, auto-asignado)', null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='¿Es un gasto recurrente? (ej: alquiler mensual)')),
                ('recurrence', models.CharField(blank=True, choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], help_text='Frecuencia de recurrencia (si es_recurrente=True)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas (N/C, referencias, etc)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('supplier', models.ForeignKey(blank=True, help_text='Proveedor (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('category', models.ForeignKey(help_text='Categoría del gasto', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['expense_date', 'category'], name='expenses_ex_expense_b82ea3_idx'), models.Index(fields=['payment_date', 'is_paid'], name='expenses_ex_payment_af06ae_idx'), models.Index(fields=['period_year', 'period_month'], name='expenses_ex_period__9b6310_idx'), models.Index(fields=['-created_at'], name='expenses_ex_created_be0371_idx')],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
    ]
