# Generated by Django 5.0.14 on 2026-08-03 17:40

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, help_text='Neto + IVA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='unique_expense_category_type_name'),
        ),
    ]
