# Generated by Django 5.0.14 on 2026-08-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expensecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='expensecategory',
            managers=[
            ],
        ),
    ]
