# Generated by Django 5.0.14 on 2026-03-31 14:33

import common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_codigo', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='precio × cantidad - descuento', max_digits=12)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje IVA (0, 10.5, 21, 27)', max_digits=5)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_linea', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Renglón de Factura',
                'verbose_name_plural': 'Renglones de Factura',
                'ordering': ['numero_linea'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(db_index=True, help_text='Número completo: PPPP-NNNNNNNN', max_length=50)),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'Factura A'), (2, 'Nota de Débito A'), (3, 'Nota de Crédito A'), (6, 'Factura B'), (7, 'Nota de Débito B'), (8, 'Nota de Crédito B'), (81, 'Tique Factura A'), (82, 'Tique Factura B'), (83, 'Tique a Consumidor Final'), (85, 'Nota de Crédito Tique A'), (86, 'Nota de Crédito Tique B'), (87, 'Nota de Crédito Tique C')], default=6, help_text='Tipo de comprobante AFIP (1=Factura A, 6=Factura B, etc.)')),
                ('punto_venta', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('numero_secuencial', models.IntegerField(default=1, help_text='Número secuencial dentro del punto de venta', validators=[django.core.validators.MinValueValidator(1)])),
                ('cliente_cuit', models.CharField(blank=True, default='', help_text='CUIT del cliente al momento de emitir', max_length=13)),
                ('cliente_razon_social', models.CharField(default='-', max_length=255)),
                ('cliente_condicion_iva', models.CharField(blank=True, default='CF', help_text='Condición IVA del cliente al emitir (RI, MONO, CF, EX)', max_length=10)),
                ('cliente_domicilio', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de (precio × cantidad) de todos los items', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma total de descuentos', max_digits=12)),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base imponible (subtotal - descuentos)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de IVA', max_digits=12)),
                ('monto_no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montos no gravados', max_digits=12)),
                ('monto_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montos exentos de IVA', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cae', models.CharField(blank=True, max_length=14)),
                ('cae_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_fiscal', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], db_index=True, default='borrador', max_length=20)),
                ('observaciones_afip', models.TextField(blank=True, default='', help_text='Errores u observaciones retornados por ARCA/AFIP')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha del comprobante (puede diferir de created_at)')),
                ('fecha_vto_pago', models.DateField(blank=True, help_text='Fecha de vencimiento del pago', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('comprobante_arca', models.OneToOneField(blank=True, help_text='Comprobante ARCA asociado (trámite fiscal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='afip.comprobante')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-number'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
    ]
