# Generated by Django 5.0.14 on 2026-08-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_invoiceitem_precio_unitario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
            ],
        ),
    ]
