# Generated by Django 5.0.14 on 2026-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_invoice_managers_alter_invoiceitem_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='motivo',
            field=models.CharField(blank=True, default='', help_text='Motivo o concepto de la Nota de Crédito / Descuento comercial o Factura', max_length=255),
        ),
    ]
