# Generated by Django on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Costo unitario de compra al momento del movimiento (al solo efecto informativo/trazabilidad).',
                max_digits=16,
                null=True,
                verbose_name='Costo unitario',
            ),
        ),
    ]
