# Generated by Django 5.0.14 on 2026-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_unit_cost'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockcount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='stockcountitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='stockmovement',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT', 'Ajuste'), ('TRANSFER', 'Transferencia'), ('LOSS', 'Pérdida'), ('RETURN', 'Devolución'), ('SALE_REVERSAL', 'Reversión de Venta')], default='ADJUSTMENT', max_length=20),
        ),
    ]
