# Generated by Django 5.0.14 on 2026-05-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pnl_monthly', 'P&L Mensual Devengado'), ('cashflow_monthly', 'Cash Flow Mensual Percibido')], db_index=True, help_text='Tipo de reporte', max_length=30)),
                ('period_year', models.PositiveSmallIntegerField(db_index=True, help_text='Año del período (ej: 2026)')),
                ('period_month', models.PositiveSmallIntegerField(db_index=True, help_text='Mes del período (1-12)')),
                ('data', models.JSONField(help_text='Reporte completo como diccionario (revenue, cogs, opex, etc)')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Cuándo se generó/actualizó')),
                ('is_stale', models.BooleanField(db_index=True, default=False, help_text='¿Marcado como obsoleto por Signal? Si True, recalcular on-the-fly')),
            ],
            options={
                'verbose_name': 'Financial Snapshot',
                'verbose_name_plural': 'Financial Snapshots',
                'indexes': [models.Index(fields=['type', 'period_year', 'period_month'], name='reports_fin_type_6cc065_idx'), models.Index(fields=['type', 'is_stale'], name='reports_fin_type_b35a6e_idx'), models.Index(fields=['-generated_at'], name='reports_fin_generat_e66a5d_idx')],
                'unique_together': {('type', 'period_year', 'period_month')},
            },
        ),
    ]
