# Generated by Django 5.0.14 on 2026-03-31 14:33

import common.models
import customers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('customer_type', models.CharField(choices=[('PERSON', 'Persona Física'), ('COMPANY', 'Empresa')], default='PERSON', max_length=10, verbose_name='Tipo de Cliente')),
                ('business_name', models.CharField(help_text='Nombre legal de la empresa o nombre completo de la persona', max_length=200, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, help_text='Nombre comercial o fantasía (opcional)', max_length=200, verbose_name='Nombre Comercial')),
                ('cuit_cuil', models.CharField(error_messages={'unique': 'Ya existe un cliente con este CUIT/CUIL/DNI.'}, help_text='Ingrese solo números (sin guiones).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Debe contener solo números, entre 7 y 11 dígitos.', regex='^\\d{7,11}$'), customers.models.validate_cuit_checksum], verbose_name='CUIT/CUIL/DNI')),
                ('tax_condition', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('NR', 'No Responsable')], default='CF', max_length=10, verbose_name='Condición IVA')),
                ('email', models.EmailField(blank=True, help_text='Email principal de contacto', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de línea', max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, help_text='Número de celular/móvil', max_length=20, verbose_name='Celular')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web (opcional)', verbose_name='Sitio Web')),
                ('contact_person', models.CharField(blank=True, help_text='Nombre de la persona de contacto principal', max_length=200, verbose_name='Persona de Contacto')),
                ('billing_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección de Facturación')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('billing_state', models.CharField(blank=True, max_length=100, verbose_name='Provincia/Estado')),
                ('billing_zip_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('billing_country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('payment_term', models.IntegerField(default=0, help_text='Días de plazo para pago (0 = contado)', verbose_name='Plazo de Pago (días)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de crédito permitido', max_digits=12, verbose_name='Límite de Crédito')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Descuento adicional específico para este cliente', max_digits=5, verbose_name='Descuento Especial (%)')),
                ('allow_credit', models.BooleanField(default=False, help_text='Si está marcado, el cliente puede comprar a crédito', verbose_name='Permite Crédito')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['business_name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(help_text='Título breve de la nota', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Contenido detallado de la nota', verbose_name='Contenido')),
                ('is_important', models.BooleanField(default=False, help_text='Marca para notas importantes o urgentes', verbose_name='Importante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='customers.customer', verbose_name='Cliente')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Nota de Cliente',
                'verbose_name_plural': 'Notas de Clientes',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(help_text='Ej: Mayorista, Minorista, Distribuidor, VIP', max_length=100, unique=True, verbose_name='Nombre del segmento')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del segmento', verbose_name='Descripción')),
                ('color', models.CharField(default='#3B82F6', help_text='Color hexadecimal para identificación visual (ej: #3B82F6)', max_length=7, verbose_name='Color')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Descuento automático aplicado a clientes de este segmento', max_digits=5, verbose_name='Descuento por defecto (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Segmento de Cliente',
                'verbose_name_plural': 'Segmentos de Clientes',
                'ordering': ['name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_segment',
            field=models.ForeignKey(blank=True, help_text='Categoría del cliente (Mayorista, Minorista, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customersegment', verbose_name='Segmento de Cliente'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cuit_cuil'], name='customers_c_cuit_cu_b1f60c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_name'], name='customers_c_busines_cf5dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'),
        ),
    ]
