# Generated by Django 5.0.14 on 2026-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_tax_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_modality',
            field=models.CharField(blank=True, choices=[('informal', 'Informal (factura al cobrar a precio actualizado)'), ('formal', 'Formal (factura al entregar)')], default='formal', help_text='Informal: se factura al cobrar a precio actualizado. Formal: se factura al entregar.', max_length=10, verbose_name='Modalidad de Cuenta Corriente'),
        ),
    ]
