# Generated by Django 5.0.14 on 2026-08-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_account_modality'),
        ('products', '0004_alter_pricelist_percentage_alter_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='Lista de precios específica para este cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='products.pricelist', verbose_name='Lista de Precios Asignada'),
        ),
    ]
