# Generated by Django 5.0.14 on 2026-08-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_price_list'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customernote',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customersegment',
            managers=[
            ],
        ),
    ]
