# Generated by Django 5.0.14 on 2026-03-31 14:33

import common.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_cuit', models.CharField(blank=True, max_length=13)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado al Cliente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('expired', 'Vencido'), ('converted', 'Convertido a Venta'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20)),
                ('is_printed', models.BooleanField(default=False, help_text='Impreso físicamente en local')),
                ('sent_via_wa', models.BooleanField(default=False, help_text='Compartido vía WhatsApp')),
                ('sent_via_email', models.BooleanField(default=False, help_text='Enviado por Correo Electrónico')),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('_cached_subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_discount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['-date', '-number'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', '%'), ('fixed', '$'), ('none', 'N/A')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('calculation_mode', models.CharField(choices=[('price_to_total', 'Auto: Edita precio → Calcula total'), ('total_to_price', 'Auto: Edita total → Calcula precio'), ('manual', 'Manual: Sin cálculos automáticos')], default='price_to_total', help_text='Define qué campo es editable', max_length=20)),
                ('target_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total deseado (solo modo "total_to_price")', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_cuit', models.CharField(blank=True, max_length=13)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('in_preparation', 'En Preparación'), ('ready', 'Lista para Entregar'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', help_text='Estado del proceso comercial', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Sin Pagar'), ('partially_paid', 'Parcialmente Pagada'), ('paid', 'Pagada Totalmente'), ('overpaid', 'Sobrepagada')], db_index=True, default='unpaid', help_text='Estado financiero', max_length=20)),
                ('fiscal_status', models.CharField(choices=[('not_required', 'No Requiere Factura'), ('pending', 'Factura Pendiente'), ('authorized', 'Factura Autorizada'), ('rejected', 'Factura Rechazada'), ('cancelled', 'Factura Anulada')], db_index=True, default='not_required', help_text='Estado ante AFIP/ARCA', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('stock_reserved_at', models.DateTimeField(blank=True, null=True)),
                ('_cached_subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_discount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('_cached_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('global_discount_type', models.CharField(choices=[('percentage', '%'), ('fixed', '$'), ('none', 'N/A')], default='none', max_length=10)),
                ('global_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('global_discount_reason', models.CharField(blank=True, max_length=200)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendiente'), ('conflict', 'Conflicto'), ('error', 'Error')], db_index=True, default='synced', editable=False, max_length=20)),
                ('local_id', models.CharField(blank=True, db_index=True, help_text='UUID del cliente offline', max_length=36, null=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Control de concurrencia optimista')),
                ('sync_last_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempt_count', models.PositiveIntegerField(default=0)),
                ('sync_error', models.TextField(blank=True)),
                ('conflict_resolution', models.CharField(blank=True, choices=[('server_wins', 'Servidor'), ('client_wins', 'Cliente'), ('manual', 'Manual')], max_length=20, null=True)),
                ('conflict_data', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('customer_segment_discount', models.ForeignKey(blank=True, help_text='Descuento por segmento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_with_segment_discount', to='customers.customersegment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_sale', to='sales.quote')),
                ('stock_reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['-date', '-number'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('original_quote_data', models.JSONField(blank=True, default=dict, help_text='Datos completos del presupuesto al momento de conversión')),
                ('modifications', models.JSONField(blank=True, default=dict, help_text='Cambios realizados durante conversión (precios, descuentos, etc.)')),
                ('converted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='sales.quote')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_quote_conversion', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Conversión de Presupuesto',
                'verbose_name_plural': 'Conversiones de Presupuestos',
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario al momento de la venta', max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo'), ('none', 'Sin Descuento')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='sales_quote_custome_47e5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['date'], name='sales_quote_date_252ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote', 'line_order'], name='sales_quote_quote_i_7f8ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'status'], name='sales_sale_custome_ceea86_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sync_status', 'sync_last_attempt'], name='sales_sale_sync_st_faf7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['local_id'], name='sales_sale_local_i_8515a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('local_id',), name='unique_local_id'),
        ),
    ]
