# Generated by Django 5.0.14 on 2026-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('debit_card', 'Tarjeta de Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('account', 'Cuenta Corriente'), ('other', 'Otro')], default='', help_text='Medio de pago principal', max_length=20),
        ),
    ]
