# Generated by Django 5.0.14 on 2026-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo unitario al momento de la venta', max_digits=16),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
