# Generated by Django 5.0.14 on 2026-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_quoteitem_unit_price_alter_saleitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_credit_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='True si la venta se registró a cuenta corriente', verbose_name='Venta a crédito'),
        ),
    ]
