# Generated by Django 5.0.14 on 2026-08-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_price_list'),
        ('sales', '0004_sale_is_credit_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer_segment_discount',
            field=models.ForeignKey(blank=True, help_text='Descuento por segmento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_with_segment_discount', to='customers.customersegment'),
        ),
        migrations.AddField(
            model_name='quote',
            name='global_discount_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='global_discount_type',
            field=models.CharField(choices=[('percentage', '%'), ('fixed', '$'), ('none', 'N/A')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='global_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
