# Generated by Django 5.0.14 on 2026-08-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quote_customer_segment_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='quoteconversion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='quoteitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sale',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='saleitem',
            managers=[
            ],
        ),
    ]
