# Generated by Django 5.0.14 on 2026-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_quote_managers_alter_quoteconversion_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='producto_nombre_override',
            field=models.CharField(blank=True, default='', help_text='Descripción personalizada para mostrador/impresión. Vacío = usa product.name', max_length=255, verbose_name='Descripción personalizada'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='producto_nombre_override',
            field=models.CharField(blank=True, default='', help_text='Descripción personalizada para mostrador/impresión. Vacío = usa product.name', max_length=255, verbose_name='Descripción personalizada'),
        ),
    ]
