# Generated by Django 5.0.14 on 2026-03-31 14:33

import common.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/categories/', verbose_name='Imagen')),
                ('order', models.IntegerField(default=0, help_text='Menor valor = aparece primero.', verbose_name='Orden de visualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(help_text='Ej: Mayorista, Tarjeta, Cliente Calandria', max_length=100, unique=True, verbose_name='Nombre')),
                ('list_type', models.CharField(choices=[('DISCOUNT', 'Bonificación (descuento)'), ('SURCHARGE', 'Recargo')], max_length=20, verbose_name='Tipo')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Valor positivo. Ej: 20 para -20% descuento o +20% recargo.', max_digits=5, verbose_name='Porcentaje')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('priority', models.IntegerField(default=0, help_text='Orden de visualización. Menor = primero.', verbose_name='Prioridad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
                'ordering': ['priority', 'name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(help_text='Código único del producto (ej: ABC-001).', max_length=100, unique=True, verbose_name='Código')),
                ('sku', models.CharField(blank=True, default='', help_text='Stock Keeping Unit. Puede coincidir con el código.', max_length=100, verbose_name='SKU')),
                ('other_codes', models.CharField(blank=True, default='', help_text='Otros códigos de referencia (ej: viejo sistema), separados por comas.', max_length=255, verbose_name='Otros códigos')),
                ('name', models.CharField(blank=True, help_text='Nombre completo. Se auto-completa con dimensiones si aplica.', max_length=200, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre.', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio base de venta sin IVA.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta (sin IVA)')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Último costo de compra sin IVA.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de costo (sin IVA)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de IVA: 21, 10.5 o 0 (exento).', max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('diameter', models.CharField(blank=True, help_text='Ej: 1/4", 8mm', max_length=50, null=True, verbose_name='Diámetro')),
                ('length', models.CharField(blank=True, help_text='Ej: 2", 50mm', max_length=50, null=True, verbose_name='Longitud')),
                ('material', models.CharField(blank=True, help_text='Ej: Acero, Inoxidable, Bronce', max_length=100, null=True, verbose_name='Material')),
                ('grade', models.CharField(blank=True, help_text='Ej: G2, G8, A2', max_length=100, null=True, verbose_name='Grado/Dureza')),
                ('norm', models.CharField(blank=True, help_text='Ej: DIN 933, ISO 4017', max_length=100, null=True, verbose_name='Norma')),
                ('colour', models.CharField(blank=True, help_text='Ej: Zincado, Negro, Natural', max_length=100, null=True, verbose_name='Color')),
                ('product_type', models.CharField(blank=True, help_text='Ej: Autoperforante, Madera, Máquina', max_length=100, null=True, verbose_name='Tipo')),
                ('form', models.CharField(blank=True, help_text='Ej: Hexagonal, Cilíndrica, Avellanada', max_length=100, null=True, verbose_name='Forma')),
                ('thread_format', models.CharField(blank=True, help_text='Ej: UNC, Métrica, Whitworth', max_length=100, null=True, verbose_name='Formato de rosca')),
                ('origin', models.CharField(blank=True, help_text='País de origen', max_length=100, null=True, verbose_name='Origen')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de barras')),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Código QR')),
                ('gtin', models.CharField(blank=True, max_length=50, null=True, verbose_name='GTIN (EAN/UPC)')),
                ('mpn', models.CharField(blank=True, max_length=100, null=True, verbose_name='MPN (Nro. de parte)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Stock mínimo')),
                ('stock_control_enabled', models.BooleanField(default=False, verbose_name='Control de stock activo')),
                ('unit_of_sale', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete'), ('METRO', 'Metro'), ('KILO', 'Kilo')], default='UNIDAD', max_length=50, verbose_name='Unidad de venta')),
                ('min_sale_unit', models.IntegerField(default=1, verbose_name='Unidad mínima de venta')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha última compra')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Último precio de compra')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='photos/products/original/', verbose_name='Imagen principal')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('refurbished', 'Reacondicionado')], default='new', max_length=20, verbose_name='Estado')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta título')),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Meta descripción')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras clave')),
                ('google_category', models.CharField(blank=True, help_text='Ej: Hardware > Fasteners > Bolts', max_length=255, null=True, verbose_name='Categoría de Google')),
                ('sold_count', models.IntegerField(default=0, verbose_name='Vendidos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('supplier', models.ForeignKey(blank=True, help_text='Proveedor principal de este producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('image', models.ImageField(upload_to='photos/products/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Texto alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es imagen principal')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='Lista de objetos {"question": "...", "answer": "..."}', verbose_name='Preguntas frecuentes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='Categoría padre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['name'],
            },
            managers=[
                ('objects', common.models.SoftDeleteManager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.subcategory', verbose_name='Subcategorías'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='products_pr_supplie_03c6c6_idx'),
        ),
    ]
