# Generated by Django 5.0.14 on 2026-07-02 13:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Último costo de compra sin IVA.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de costo (sin IVA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Último precio de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Precio base de venta sin IVA.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta (sin IVA)'),
        ),
    ]
