# Generated by Django 5.0.14 on 2026-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cost_alter_product_last_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='percentage',
            field=models.DecimalField(decimal_places=6, help_text='Valor positivo. Ej: 20 para -20% descuento o +20% recargo.', max_digits=10, verbose_name='Porcentaje'),
        ),
    ]
