# Generated by Django 5.0.14 on 2026-08-02 05:40

import django.core.validators
import products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_pricelist_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='percentage',
            field=models.DecimalField(decimal_places=6, help_text='Valor positivo. Ej: 20 para -20% descuento o +20% recargo.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de IVA: 21, 10.5 o 0 (exento).', max_digits=5, validators=[products.models.validate_afip_tax_rate], verbose_name='Tasa de IVA (%)'),
        ),
    ]
