# Generated by Django 5.0.14 on 2026-08-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pricelist_percentage_alter_product_tax_rate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pricelist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
            ],
        ),
    ]
